#Website info to import
id: 1
name: Mojitech
url: https://mojitech.net/
imageRef:
operatingDaysOpenning: Monday
operatingDaysClosing: Saturday
operatingHoursOpenning: 9
operatingHoursOpenningPeriod: AM
operatingHoursClosing: 6
operatingHoursClosingPeriod: PM
operatingHoursWeekendOpenning: 9
operatingHoursWeekendOpenningPeriod: AM
operatingHoursWeekendClosing: 1
operatingHoursWeekendClosingPeriod: PM
currency: $
pricesIncludingVAT: false
vatPercent: 11
contactAddress: New Rawda – Cabella St. Georges Street – Beirut, Lebanon
contactEmail: sales@mojitech.net  |  support@mojitech.net
contactNumber1: 009613417443
contactNumber2: 009611693444
contactNumber3:
Xpath: //div[@class='item-info']
productNameXpath: .//div[@class='item-title']/a[@href]
productPriceXpath: .//span[@class='woocs_price_code']/ins
productUrlXpath: .//div[@class='item-title']/a
productAltXpath1: .//span[@class='woocommerce-Price-amount amount']
productAltXpath2:
productAltXpath3:
cpuUrl:
  - https://mojitech.net/product-category/pc-parts/cpus/?currency=USD
  - https://mojitech.net/product-category/pc-parts/cpus/page/2/?currency=USD
computercaseUrl:
  - https://mojitech.net/product-category/pc-parts/computer-cases/?currency=USD
  - https://mojitech.net/product-category/pc-parts/computer-cases/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/computer-cases/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/computer-cases/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/computer-cases/page/5/?currency=USD
  - https://mojitech.net/product-category/pc-parts/computer-cases/page/6/?currency=USD
coolingfanUrl:
  - https://mojitech.net/product-category/pc-parts/cooling/?currency=USD
  - https://mojitech.net/product-category/pc-parts/cooling/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/cooling/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/cooling/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/cooling/page/5/?currency=USD
memoryUrl:
  - https://mojitech.net/product-category/pc-parts/memory/?currency=USD
  - https://mojitech.net/product-category/pc-parts/memory/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/memory/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/memory/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/memory/page/5/?currency=USD
motherboardUrl:
  - https://mojitech.net/product-category/pc-parts/motherboards/?currency=USD
  - https://mojitech.net/product-category/pc-parts/motherboards/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/motherboards/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/motherboards/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/motherboards/page/5/?currency=USD
psuUrl:
  - https://mojitech.net/product-category/pc-parts/power-supplies/?currency=USD
  - https://mojitech.net/product-category/pc-parts/power-supplies/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/power-supplies/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/power-supplies/page/4/?currency=USD
storageUrl:
  - https://mojitech.net/product-category/pc-parts/storage/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/5/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/6/?currency=USD
  - https://mojitech.net/product-category/pc-parts/storage/page/7/?currency=USD
graphiccardUrl:
  - https://mojitech.net/product-category/pc-parts/video-cards/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/2/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/3/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/4/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/5/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/6/?currency=USD
  - https://mojitech.net/product-category/pc-parts/video-cards/page/7/?currency=USD
laptopUrl:
  -
accessoriesUrl:
  -
